sudo: false
language: java
jdk:
  - oraclejdk11
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8
  - oraclejdk7
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8
  - openjdk7
  - openjdk6

env:
- TERM=dumb

after_success:
- gradle cobertura coveralls
